---
fixtures:
  repositories:
    common: "git://github.com/simp/pupmod-simp-common"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    elasticsearch: "git://github.com/elastic/puppet-elasticsearch"
  symlinks:
    simp_elasticsearch: "#{source_dir}"
